version: '3.8'

services:
  app:
    build:
      context: .            # Définit le dossier racine comme contexte
      dockerfile: Backend/Dockerfile  # Chemin du Dockerfile dans Backend
    image: ansible          # Nom de l'image Docker
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: ["redis-server", "--port", "6380"]
    ports:
      - "6380:6380" # Changer le port externe et interne à 6380

volumes:
  playbooks:
    driver: local
